use serde::Deserialize;
#[derive(Debug, Deserialize)]
pub struct Player {
  pub acceleration: i32,
  pub marking: i32,
  pub strength: i32,
  pub dribbling: i32,
  pub name: String,
  pub stamina: i32,
  pub long_passing: i32,
  pub standing_tackle: i32,
  pub sliding_tackle: i32,
  pub ball_control: i32,
  pub passing: i32,
  pub interceptions: i32,
  pub agility: i32,
  pub long_shots: i32,
  pub shot_power: i32,
  pub pos: String,
  pub jumping: i32,
  pub positioning: i32,
  pub curve: i32,
  pub sprint_speed: i32,
  pub crossing: i32,
  pub finishing: i32,
  pub balance: i32,
  pub heading: i32,
  pub vision: i32,
  pub ovr: i32,
  pub reactions: i32,
  pub free_kick: i32,
  pub short_passing: i32,
  pub pace: i32,
  pub penalties: i32,
  pub defending: i32,
  pub volleys: i32,
  pub shooting: i32,
  pub aggression: i32,
  pub physical: i32,
}